version: 2.0
jobs:
  build:
    docker:
     - image: jsii/superchain
    steps:
      - run:
          name: fix ssh permissions
          command: chmod 600 /root/.ssh/config
      - checkout
      - run:
          name: install
          command: yarn install --frozen-lockfile
      - run:
          name: build
          command: yarn build
      - run:
          name: test
          command: yarn test
      - run:
          name: package
          command: yarn package
          no_output_timeout: 30m
      - run:
          name: publish to npm
          command: |
            npx jsii-release-npm dist/js
      - run:
          name: publish to pypi
          command: |
            npx jsii-release-pypi dist/python
      - run:
          name: publish to maven
          command: |
            npx jsii-release-maven dist/java
      - run:
          name: publish to nuget
          command: |
            npx jsii-release-nuget dist/dotnet